version: "3.8"

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
      MYSQL_DATABASE: test_database
    networks:
      - db_network
  app:
    image: dawids21/mysql-docker-java-test
    build: ./java-app
    networks:
      - db_network
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:3306", "--", "java", "-jar", "target/mysql-docker-java-test-1.0-SNAPSHOT-jar-with-dependencies.jar"]

networks:
  db_network: